### ISSUE TITLE
MPI error

### ISSUE THREAD

**Issue by CanLi1** [HrgaT/MADAM#1]
Hello,

First of all, thanks for sharing the code. I just installed your package and ran `./admm Instances/rudy/g05_100.0 params` in the directory. I got the following error. Any suggestions on what might go wrong? Thanks in advance!
Number of cores: 1
Input file: Instances/rudy/g05_100.0

Graph has 100 vertices and 2475 edges.
Root node bound: 1441.20
Initial lower bound: 1430
[dantzig:31345] *** An error occurred in MPI_Send
[dantzig:31345] *** reported by process [670957569,0]
[dantzig:31345] *** on communicator MPI_COMM_WORLD
[dantzig:31345] *** MPI_ERR_RANK: invalid rank
[dantzig:31345] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[dantzig:31345] ***    and potentially your MPI job)

**Comment by HrgaT** [comment]
Dear Can,

thank you for trying MADAM and for your feedback. It is my mistake that I
did not include the README file specifying that the parallel code works
only if the number of cores is at least 3, ie one load coordinator and 2
workers.
Also the run command is then

mpirun -n #cores ./admm Instances/rudy/g05_100.0

Best regards,
Timotej Hrga

V V tor., 17. avg. 2021 ob 02:52 je oseba Can Li ***@***.***>
napisala:

**Comment by CanLi1** [comment]
Hi Timotej,

Many thanks for your quick reply. I have 20 cores on my server and tried `mpirun -n 5 ./admm Instances/rudy/g05_100.0` but it has the following error.  Also, is there a command that the code can run with only one core.
[dantzig:19153] *** Process received signal ***
[dantzig:19153] Signal: Segmentation fault (11)
[dantzig:19153] Signal code: Address not mapped (1)
[dantzig:19153] Failing at address: (nil)
[dantzig:19154] *** Process received signal ***
[dantzig:19154] Signal: Segmentation fault (11)
[dantzig:19154] Signal code: Address not mapped (1)
[dantzig:19154] Failing at address: (nil)
[dantzig:19153] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f22256f1fd0]
[dantzig:19153] [ 1] ./admm(+0x5d1b)[0x5603dbc66d1b]
[dantzig:19153] [ 2] ./admm(+0x1cdb)[0x5603dbc62cdbNumber of cores: 5

Nodes = 0
[dantzig:19152] *** Process received signal ***
[dantzig:19152] Signal: Segmentation fault (11)
[dantzig:19152] Signal code: Address not mapped (1)
[dantzig:19152] Failing at address: (nil)
[dantzig:19154] [ 0] [dantzig:19155] *** Process received signal ***
[dantzig:19155] Signal: Segmentation fault (11)
[dantzig:19155] Signal code: Address not mapped (1)
[dantzig:19155] Failing at address: (nil)
Usage: ./biqbin file.rudy file.params
]
[dantzig:19153] [ 3] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f22256d4b97]
[dantzig:19153] [ 4] ./admm(+0x228a)[0x5603dbc6328a]
[dantzig:19153] *** End of error message ***
Root node bound = 0.00
Maximum value = 0
Solution = ( )
Time = 0.00 s

[dantzig:19151] *** Process received signal ***
[dantzig:19152] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f3025f6ffd0]
[dantzig:19154] [ 1] ./admm(+0x5d1b)[0x55fb9f937d1b]
[dantzig:19154] [ 2] ./admm(+0x1cdb)[0x55fb9f933cdb]
[dantzig:19154] [ 3] [dantzig:19155] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f9733f08fd0]
[dantzig:19155] [ 1] ./admm(+0x5d1b)[0x558a13ac3d1b]
[dantzig:19155] [ 2] ./admm[dantzig:19151] Signal: Segmentation fault (11)
[dantzig:19151] Signal code: Address not mapped (1)
[dantzig:19151] Failing at address: (nil)
[dantzig:19151] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f06d8283fd0]
[dantzig:19152] [ 1] ./admm(+0x5d1b)[0x558d0dd5bd1b]
[dantzig:19152] [ 2] ./admm(+0x1cdb)[0x558d0dd57cdb]
[dantzig:19152] [ 3] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f3025f52b97]
[dantzig:19154] [ 4] ./admm(+0x228a)[0x55fb9f93428a]
[dantzig:19154] *** End of error message ***
(+0x1cdb)[0x558a13abfcdb]
[dantzig:19155] [ 3] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f06d8266b97]
[dantzig:19152] [ 4] ./admm(+0x228a)[0x558d0dd5828a]
[dantzig:19152] *** End of error message ***
/lib/x86_64-linux-gnu/libc.so.6(+0x3efd0)[0x7f9cfb1f2fd0]
[dantzig:19151] [ 1] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f9733eebb97]
[dantzig:19155] [ 4] ./admm(+0x228a)[0x558a13ac028a]
[dantzig:19155] *** End of error message ***
/lib/x86_64-linux-gnu/libc.so.6(__fprintf_chk+0x6b)[0x7f9cfb2e65db]
[dantzig:19151] [ 2] ./admm(+0x688e)[0x5644b8b7488e]
[dantzig:19151] [ 3] ./admm(+0x1c7a)[0x5644b8b6fc7a]
[dantzig:19151] [ 4] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f9cfb1d5b97]
[dantzig:19151] [ 5] ./admm(+0x228a)[0x5644b8b7028a]
[dantzig:19151] *** End of error message ***
--------------------------------------------------------------------------
mpirun noticed that process rank 1 with PID 0 on node dantzig exited on signal 11 (Segmentation fault).
--------------------------------------------------------------------------

**Comment by HrgaT** [comment]
Dear Can,

In the previous post I forgot the parameter file that comes as the last
argument. Therefore, with 20 cores try

mpirun -n 20 ./admm Instances/rudy/g05_100.0 params

I have a separate code for the serial version of MADAM that was updated
with some minor changes.
It is on my todo list to merge the solvers so the algorithm automatically
decides which version to use based on the number of cores.

BR, Timotej

V V tor., 17. avg. 2021 ob 16:34 je oseba Can Li ***@***.***>
napisala:

**Comment by CanLi1** [comment]
It works now. Many thanks for your help!
